#!/usr/bin/with-contenv bash

# make our folders
echo "================== make /config =========="
mkdir -p \
	/config/{nginx/site-confs,www,log/nginx,keys,log/php} \
	/run \
	/var/lib/nginx/tmp/client_body \
	/var/tmp/nginx

# copy config files
[[ ! -f /config/nginx/nginx.conf ]] && \
	echo "copy /defaults/nginx.conf to /config/nginx/nginx.conf"
	cp /defaults/nginx.conf /config/nginx/nginx.conf
	ls -al /config/nginx/
[[ ! -f /config/nginx/site-confs/default ]] && \
	echo "copy /defaults/default to /config/nginx/site-confs/default"
	cp /defaults/default /config/nginx/site-confs/default
	ls -al /config/nginx/site-confs/

# permissions
source /etc/hluser

chown -R $HL_USER_USERNAME:$HL_USER_USERNAME \
	/config \
	/run \
	/var/lib/nginx \
	/var/tmp/nginx 
chmod -R g+w \
	/config/{nginx,www}
chmod -R 644 /etc/logrotate.d

# permissions /opt/www
chown -R $HL_USER_USERNAME:$HL_USER_USERNAME /opt/www
